Add release trigger

diff --git a/.github/workflows/prerelease.yml b/.github/workflows/prerelease.yml
--- a/.github/workflows/prerelease.yml
+++ b/.github/workflows/prerelease.yml
@@ -72,3 +72,22 @@ jobs:
       run: |
         curl -X POST -H "Authorization: token ${{secrets.GITHUB_TOKEN}}" -H "Content-Type: application/octet-stream" -T www.tar.gz "${{env.releaseurl}}"
 
+  updatecakemix:
+    runs-on: ubuntu-latest
+    needs: prerelease
+    steps:
+    - name: update cakemix repo
+      env:
+        CAKEMIX_SSHKEY: ${{secrets.CAKEMIX_SSHKEY}}
+      run: |
+        mkdir ~/.ssh
+        echo "${CAKEMIX_SSHKEY}" > ~/.ssh/id_rsa
+        chmod 600 ~/.ssh/id_rsa
+        git clone git@github.com:wonder-wonder/cakemix.git
+        cd cakemix
+        git checkout develop && git submodule init && git submodule update
+        cd cakemix-server && git checkout develop && git pull && cd ..
+        cd cakemix-front && git checkout develop && git pull && cd ..
+        git config --global user.email "github@actions"
+        git config --global user.name "github-actions"
+        git add . && git commit -m "Update for develop" && git push || echo "Nothing to update. Abort."
diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -124,3 +124,24 @@ jobs:
             base: "develop",
             title: "chore: ${{ env.newtag }} to develop"
           });
+
+  updatecakemix:
+    runs-on: ubuntu-latest
+    if: always()
+    needs: [release, hotfix]
+    steps:
+    - name: update cakemix repo
+      env:
+        CAKEMIX_SSHKEY: ${{secrets.CAKEMIX_SSHKEY}}
+      run: |
+        mkdir ~/.ssh
+        echo "${CAKEMIX_SSHKEY}" > ~/.ssh/id_rsa
+        chmod 600 ~/.ssh/id_rsa
+        git clone git@github.com:wonder-wonder/cakemix.git
+        cd cakemix
+        git checkout main && git submodule init && git submodule update
+        cd cakemix-server && git checkout main && git pull && cd ..
+        cd cakemix-front && git checkout main && git pull && cd ..
+        git config --global user.email "github@actions"
+        git config --global user.name "github-actions"
+        git add . && git commit -m "Update for main" && git push || echo "Nothing to update. Abort."
